_BASE_: "../base_rcnn_fpn.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ('tuft_train', )
  TEST: ('tuft_test', )
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000